package com.example.treeplantingapp

class CountyTreeRepository {
    companion object {
        private val meruCode = 1
        private val baringoCode = 2
        private val taitaCode = 3
        private val kituiCode = 4

        fun getMeruData(): ArrayList<CountyTree> = arrayListOf(
            CountyTree(1,
                countyCode = meruCode,
                "Kei Apple",
                "Hedge"),
            CountyTree(2,
                countyCode = meruCode,
                "Brachylaena huillensis ",
                "Timber,Fencing,Carving"),
            CountyTree(3,
                countyCode = meruCode,
                "Blue Gum",
                "Timber, Fencing, Poles"),
            CountyTree(4,
                countyCode = meruCode,
                "Olea africana",
                "Fencing, Posts, Wood Fuel"),
            CountyTree(5,
                countyCode = meruCode,
                "Brancylaena huillensis ",
                "Timber, Fencing, Carving"),
            CountyTree(6,
                countyCode = meruCode,
                "Prunus africanum",
                "Timber"),
            CountyTree(7,
                countyCode = meruCode,
                "Brachystegia spiciformis ",
                "Timber"),
            CountyTree(8,
                countyCode = meruCode,
                "Cupressus lusitanica",
                "Timber,Hedge,Shelter"),
            CountyTree(9,
                countyCode = meruCode,
                "Jacaranda",
                "Amenity"),
            CountyTree(10,
                countyCode = meruCode,
                "Schinus molle",
                "Amenity,Fuel"),
            CountyTree(11,
                countyCode = meruCode,
                "Azadirachta indica",
                "Amenity, Fuel, Fencing, medical"),
            CountyTree(12,
                countyCode = meruCode,
                "Acacia xanthophloea",
                "Soil Conservation, Water Conservation")
        )

        fun getTaitaData(): ArrayList<CountyTree> = arrayListOf(
            CountyTree(0,
                countyCode = taitaCode,
                "Mukau",
                "timber, firewood, charcoal, shade, soil stabilization"),
            CountyTree(1,
                countyCode = taitaCode,
                "Umbrella tree",
                "fodder, fuelwood, medicinal uses"),
            CountyTree(2,
                countyCode = taitaCode,
                "Australian pine",
                "timber, fuelwood, windbreak"),
            CountyTree(3,
                countyCode = taitaCode,
                "Silky oak",
                "shade, timber, fuelwood"),
            CountyTree(4,
                countyCode = taitaCode,
                "Rose gum",
                "timber, pulp, paper production, shade, windbreak"),
            CountyTree(5,
                countyCode = taitaCode,
                "Mathenge",
                "fuelwood, fodder, gum"),
            CountyTree(6,
                countyCode = taitaCode,
                "East African greenheart",
                "timber, medicine, shade")

        )

        fun getBaringoData(): ArrayList<CountyTree> = arrayListOf(
            CountyTree(0,
                countyCode = baringoCode,
                "Acacia tortilis",
                "provides shade, fodder for livestock, and its bark can be used for medicinal purposes"),
            CountyTree(1,
                countyCode = baringoCode,
                "Balanites aegyptiaca",
                "its fruits are edible and rich in nutrients, and the tree is also used for its medicinal properties"),
            CountyTree(2,
                countyCode = baringoCode,
                "Prosopis juliflora",
                "provides shade, and its wood is used for fuel and construction"),
            CountyTree(3,
                countyCode = baringoCode,
                "Senna spectabilis",
                "its bark and leaves are used for medicinal purposes, and it is also used as a shade tree"),
            CountyTree(4,
                countyCode = baringoCode,
                "Azadirachta indica",
                " traditional medicine; its leaves are also used as a natural pesticide"),
            CountyTree(5,
                countyCode = baringoCode,
                "Moringa oleifera",
                "used for its leaves as a food supplement")
        )

        fun getKituiData(): ArrayList<CountyTree> = arrayListOf(
            CountyTree(0,
                countyCode = kituiCode,
                "Melia volkensii",
                "Used for timber, construction, and medicinal purposes"),
            CountyTree(1,
                countyCode = kituiCode,
                "Acacia senegal",
                "Grown for its gum, which is used in food, cosmetics, and pharmaceuticals, and as a source of fuelwood"),
            CountyTree(2,
                countyCode = kituiCode,
                "Faidherbia albida",
                "Drought-resistant and used for nitrogen fixation and as fodder for livestock"),
            CountyTree(3,
                countyCode = kituiCode,
                "Azadirachta indica",
                "Known for its medicinal properties and leaves are used as a natural pesticide"),
            CountyTree(4,
                countyCode = kituiCode,
                "Moringa oleifera",
                "Leaves are rich in vitamins and minerals and can be eaten fresh or dried and used as a food supplement"),
            CountyTree(5,
                countyCode = kituiCode,
                "Croton megalocarpus",
                "Grown for its oil, which is used for cooking, lighting, soap making, and medicinal purposes")
        )
    }
}